export type Position = {
  left: 'left';
  right: 'right';
};

export const CATEGORY_NEWS = [
  { name: 'news.categories.business', value: 'business' },
  { name: 'news.categories.entertainment', value: 'entertainment' },
  { name: 'news.categories.general', value: 'general' },
  { name: 'news.categories.health', value: 'health' },
  { name: 'news.categories.science', value: 'science' },
  { name: 'news.categories.sports', value: 'sports' },
  { name: 'news.categories.technology', value: 'technology' },
];

export const COUNTRIES = [
  { name: 'news.countries.emirate', value: 'ae' },
  { name: 'news.countries.argentina', value: 'ar' },
  { name: 'news.countries.austria', value: 'at' },
  { name: 'news.countries.australia', value: 'au' },
  { name: 'news.countries.belgium', value: 'be' },
  { name: 'news.countries.bulgaria', value: 'bg' },
  { name: 'news.countries.brazil', value: 'br' },
  { name: 'news.countries.canada', value: 'ca' },
  { name: 'news.countries.switzerland', value: 'ch' },
  { name: 'news.countries.china', value: 'cn' },
  { name: 'news.countries.colombia', value: 'co' },
  { name: 'news.countries.cuba', value: 'cu' },
  { name: 'news.countries.czech', value: 'cz' },
  { name: 'news.countries.germany', value: 'de' },
  { name: 'news.countries.egypt', value: 'eg' },
  { name: 'news.countries.france', value: 'fr' },
  { name: 'news.countries.united-kingdom', value: 'gb' },
  { name: 'news.countries.greece', value: 'gr' },
  { name: 'news.countries.hong-kong', value: 'hk' },
  { name: 'news.countries.hungary', value: 'hu' },
  { name: 'news.countries.indonesia', value: 'id' },
  { name: 'news.countries.ireland', value: 'ie' },
  { name: 'news.countries.israel', value: 'il' },
  { name: 'news.countries.india', value: 'in' },
  { name: 'news.countries.italy', value: 'it' },
  { name: 'news.countries.japan', value: 'jp' },
  { name: 'news.countries.korea', value: 'kr' },
  { name: 'news.countries.lithuania', value: 'lt' },
  { name: 'news.countries.latvia', value: 'lv' },
  { name: 'news.countries.morocco', value: 'ma' },
  { name: 'news.countries.mexico', value: 'mx' },
  { name: 'news.countries.malaysia', value: 'my' },
  { name: 'news.countries.nigeria', value: 'ng' },
  { name: 'news.countries.netherlands', value: 'nl' },
  { name: 'news.countries.norway', value: 'no' },
  { name: 'news.countries.new-zealand', value: 'nz' },
  { name: 'news.countries.philippines', value: 'ph' },
  { name: 'news.countries.poland', value: 'pl' },
  { name: 'news.countries.portugal', value: 'pt' },
  { name: 'news.countries.romania', value: 'ro' },
  { name: 'news.countries.serbia', value: 'rs' },
  { name: 'news.countries.russia', value: 'ru' },
  { name: 'news.countries.saudi-arabia', value: 'sa' },
  { name: 'news.countries.sweden', value: 'se' },
  { name: 'news.countries.singapore', value: 'sg' },
  { name: 'news.countries.slovenia', value: 'si' },
  { name: 'news.countries.slovakia', value: 'sk' },
  { name: 'news.countries.thailand', value: 'th' },
  { name: 'news.countries.turkey', value: 'tr' },
  { name: 'news.countries.republic-china', value: 'tw' },
  { name: 'news.countries.ukraine', value: 'ua' },
  { name: 'news.countries.united-states', value: 'us' },
  { name: 'news.countries.venezuela', value: 've' },
  { name: 'news.countries.south-africa', value: 'za' },
];
